@startuml

title __PROG_LAB4's Class Diagram__\n

  package  {
    package ifmo.programming.lab5 {
      class Building {
      }
    }
  }
  

  package  {
    package ifmo.programming.lab5 {
      class BuildingChecker {
      }
    }
  }
  

  package  {
    package ifmo.programming.lab5 {
      abstract class Furnishings {
      }
    }
  }
  

  package  {
    package com.company.lib {
      class JSONArray {
      }
    }
  }
  

  package  {
    package com.company.lib {
      class JSONBoolean {
      }
    }
  }
  

  package  {
    package com.company.lib {
      class JSONEntity {
      }
    }
  }
  

  package  {
    package com.company.lib {
      class JSONNumber {
      }
    }
  }
  

  package  {
    package com.company.lib {
      class JSONObject {
      }
    }
  }
  

  package  {
    package com.company.lib {
      class JSONParseException {
      }
    }
  }
  

  package  {
    package com.company.lib {
      class JSONParser {
      }
    }
  }
  

  package  {
    package com.company.lib {
      class JSONParser {
      }
    }
  }
  

  package  {
    package com.company.lib {
      enum JSONType {
      }
    }
  }
  

  package  {
    class Main {
    }
  }
  

  package  {
    package ifmo.programming.lab5 {
      class Main {
      }
    }
  }
  

  package  {
    class Main {
    }
  }
  

  package  {
    package ifmo.programming.lab5 {
      class Room {
      }
    }
  }
  

  package  {
    package ifmo.programming.lab5 {
      class RoomFactory {
      }
    }
  }
  

  Room -up-|> Comparable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
